dataset:
  name: CIFAR-10
  num_classes: 10
  test_samples: 10000
  train_samples: 50000
experiment_info:
  aux_positions: ''
  cbam_positions: 1,2
  model_type: hybrid
  name: hybrid_se15-16_cbam1-2
  se_positions: 15,16
  timestamp: 2025-10-25_18-56-15
hyperparameters:
  accumulation_steps: 2
  amp: true
  batch_size: 64
  epochs: 200
  learning_rate: 0.01
  optimizer: AdamW
  scheduler: OneCycleLR
  weight_decay: 0.0001
model_architecture:
  aux_positions: ''
  cbam_positions: 1,2
  num_classes: 10
  se_positions: 15,16
  type: hybrid
training_info:
  device: cuda
  device_name: NVIDIA GeForce RTX 4060 Ti
